# Generated by Django 4.2.5 on 2023-10-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_course_price_lesson_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_preview',
            new_name='preview',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_preview',
            new_name='preview',
        ),
    ]
